//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int customerId { get; set; }
        public string customerAdress { get; set; }
        public string customerPhone1 { get; set; }
        public string customerPhone2 { get; set; }
        public string customerFirstName { get; set; }
        public string customerLastName { get; set; }
    
        public virtual User User { get; set; }
    }
}
