//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpeningHour
    {
        public int openingHourID { get; set; }
        public int branchId { get; set; }
        public int fromDay { get; set; }
        public int toDay { get; set; }
        public System.TimeSpan fromHour { get; set; }
        public System.TimeSpan toHour { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
