//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int priceId { get; set; }
        public int sheetTypeId { get; set; }
        public bool selfDesign { get; set; }
        public decimal price1 { get; set; }
    
        public virtual SheetsType SheetsType { get; set; }
    }
}
